// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketRaisingLibrary.Models;

#nullable disable

namespace TicketRaisingLibrary.Migrations
{
    [DbContext(typeof(TicketPortalDBContext))]
    partial class TicketPortalDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketRaisingLibrary.Models.Department", b =>
                {
                    b.Property<string>("DeptId")
                        .HasColumnType("CHAR(4)");

                    b.Property<string>("DeptName")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("DeptId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("TicketRaisingLibrary.Models.Employee", b =>
                {
                    b.Property<string>("EmpId")
                        .HasColumnType("CHAR(4)");

                    b.Property<string>("DeptId")
                        .HasColumnType("CHAR(4)");

                    b.Property<string>("EmpName")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Password")
                        .HasColumnType("VARCHAR(15)");

                    b.Property<string>("Role")
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("EmpId");

                    b.HasIndex("DeptId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("TicketRaisingLibrary.Models.SLA", b =>
                {
                    b.Property<string>("SLAId")
                        .HasColumnType("CHAR(4)");

                    b.Property<string>("Priority")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<int>("ResolutionHours")
                        .HasColumnType("int");

                    b.Property<int>("ResponseTime")
                        .HasColumnType("int");

                    b.Property<string>("SLAName")
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("SLAId");

                    b.ToTable("SLA");
                });

            modelBuilder.Entity("TicketRaisingLibrary.Models.Ticket", b =>
                {
                    b.Property<string>("TicketId")
                        .HasColumnType("CHAR(4)");

                    b.Property<string>("AssignedToEmpId")
                        .HasColumnType("CHAR(4)");

                    b.Property<string>("CreatedByEmpId")
                        .HasColumnType("CHAR(4)");

                    b.Property<string>("Description")
                        .HasColumnType("CHAR(50)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TicketCreatedDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("TicketTypeId")
                        .HasColumnType("CHAR(4)");

                    b.Property<string>("Title")
                        .HasColumnType("CHAR(100)");

                    b.HasKey("TicketId");

                    b.HasIndex("AssignedToEmpId");

                    b.HasIndex("CreatedByEmpId");

                    b.HasIndex("TicketTypeId");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("TicketRaisingLibrary.Models.TicketReply", b =>
                {
                    b.Property<string>("ReplyId")
                        .HasColumnType("CHAR(6)");

                    b.Property<string>("ReplyByAssignedEmpId")
                        .HasColumnType("CHAR(4)");

                    b.Property<string>("ReplyByCreatorEmpId")
                        .HasColumnType("CHAR(4)");

                    b.Property<string>("ReplyMessage")
                        .HasColumnType("CHAR(100)");

                    b.Property<string>("TicketId")
                        .HasColumnType("CHAR(4)");

                    b.HasKey("ReplyId");

                    b.HasIndex("ReplyByAssignedEmpId");

                    b.HasIndex("ReplyByCreatorEmpId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketReply");
                });

            modelBuilder.Entity("TicketRaisingLibrary.Models.TicketType", b =>
                {
                    b.Property<string>("TicketTypeId")
                        .HasColumnType("CHAR(4)");

                    b.Property<string>("DeptId")
                        .HasColumnType("CHAR(4)");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("SLAId")
                        .HasColumnType("CHAR(4)");

                    b.Property<string>("TypeName")
                        .HasColumnType("VARCHAR(30)");

                    b.HasKey("TicketTypeId");

                    b.HasIndex("DeptId");

                    b.HasIndex("SLAId");

                    b.ToTable("TicketTypes");
                });

            modelBuilder.Entity("TicketRaisingLibrary.Models.Employee", b =>
                {
                    b.HasOne("TicketRaisingLibrary.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DeptId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("TicketRaisingLibrary.Models.Ticket", b =>
                {
                    b.HasOne("TicketRaisingLibrary.Models.Employee", "AssignedToEmployee")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("AssignedToEmpId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TicketRaisingLibrary.Models.Employee", "CreatedByEmployee")
                        .WithMany("CreatedTickets")
                        .HasForeignKey("CreatedByEmpId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TicketRaisingLibrary.Models.TicketType", "TicketType")
                        .WithMany("Tickets")
                        .HasForeignKey("TicketTypeId");

                    b.Navigation("AssignedToEmployee");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("TicketType");
                });

            modelBuilder.Entity("TicketRaisingLibrary.Models.TicketReply", b =>
                {
                    b.HasOne("TicketRaisingLibrary.Models.Employee", "ReplyByAssigned")
                        .WithMany("AssignedReplies")
                        .HasForeignKey("ReplyByAssignedEmpId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TicketRaisingLibrary.Models.Employee", "ReplyByCreator")
                        .WithMany("CreatorReplies")
                        .HasForeignKey("ReplyByCreatorEmpId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TicketRaisingLibrary.Models.Ticket", "Ticket")
                        .WithMany("TicketReplies")
                        .HasForeignKey("TicketId");

                    b.Navigation("ReplyByAssigned");

                    b.Navigation("ReplyByCreator");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TicketRaisingLibrary.Models.TicketType", b =>
                {
                    b.HasOne("TicketRaisingLibrary.Models.Department", "Department")
                        .WithMany("TicketTypes")
                        .HasForeignKey("DeptId");

                    b.HasOne("TicketRaisingLibrary.Models.SLA", "SLA")
                        .WithMany("TicketTypes")
                        .HasForeignKey("SLAId");

                    b.Navigation("Department");

                    b.Navigation("SLA");
                });

            modelBuilder.Entity("TicketRaisingLibrary.Models.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("TicketTypes");
                });

            modelBuilder.Entity("TicketRaisingLibrary.Models.Employee", b =>
                {
                    b.Navigation("AssignedReplies");

                    b.Navigation("AssignedTickets");

                    b.Navigation("CreatedTickets");

                    b.Navigation("CreatorReplies");
                });

            modelBuilder.Entity("TicketRaisingLibrary.Models.SLA", b =>
                {
                    b.Navigation("TicketTypes");
                });

            modelBuilder.Entity("TicketRaisingLibrary.Models.Ticket", b =>
                {
                    b.Navigation("TicketReplies");
                });

            modelBuilder.Entity("TicketRaisingLibrary.Models.TicketType", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
